name: 'user_events'
version: '1.0.0'
config-version: 2

profile: 'user_events'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  user_events:
    +materialized: table
    marts:
      +materialized: incremental
